### ISSUE TITLE
BookSonic does not see files correctly

### ISSUE THREAD

**Issue by goose-ws** [linuxserver/docker-booksonic#17]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

If you are new to Docker or this application our issue tracker is **ONLY** used for reporting bugs or requesting features. Please use [our discord server](https://discord.gg/YWrKVTn) for general support.

------------------------------

## Expected Behavior
Files appear in BookSonic

## Current Behavior
Files do not appear unless a specific chain of events is followed

## Steps to Reproduce
1. Install BookSonic in Docker via the DockStarter tool
2. Ensure that my user has permissions to access the media folder
3. Verify that the `/audiobooks` volume is mounted correctly, and readable inside the docker container. I did this by connecting to a console in the container, `cd`ing to the directory, opening the files with `head`, and verifying write permissions with `touch`. The directory structure I'm using is: `/Audiobooks/Andy Weir/The Martian/The Martian (Unabridged).flac`
4. Add the media folder via `Settings > Media folders > Name "Audio Books" > Folder "/audiobooks" > Enabled "X"`
5. Click `Save`
6. Click `Scan media folders now`
7. Return to `Home`, see that no media is present.
8. Return to `Settings > Media folders`, change the path for `Audio Books` to `/audiobooksss` (A directory which does not exist)
9. Click `Save`
10. Click `Scan media folders now`
11. Change the path for `Audio Books` to `/audiobooks` (The correct/actual directory)
12. Click `Save`
13. Click `Scan media folders now`
14. Return to `Home`, where my media is now present.

Another user reported similar behavior on Reddit ([link](https://old.reddit.com/r/Booksonic/comments/byyaks/not_recognizing_files_not_sure_if_anyone_is/) who was told it was an issue related to their files being on Google Drive. My files are on a local drive, `/mnt/storage` is a MergerFS mount point of `/mnt/disk*` -- However, all disks are local and connected directly via LSI.

## Environment
**OS:** Debian 10
**CPU architecture:** x86_64
**How docker service was installed:** DockStarter

## Command used to create docker container (run/create/compose/screenshot)

Relevant portion of `docker-compose.yml`:
```
  booksonic:
    container_name: booksonic
    environment:
    - CONTEXT_PATH=/booksonic
    - PGID=1000
    - PUID=1000
    - TZ=US/Eastern
    hostname: Vergil
    image: linuxserver/booksonic
    logging:
      driver: json-file
      options:
        max-file: 10
        max-size: 200k
    ports:
    - 8040:4040
    restart: unless-stopped
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /home/goose/.config/appdata/booksonic:/config
    - /home/goose/.config/appdata/shared:/shared
    - /mnt/storage/media/Audiobooks:/audiobooks
    - /mnt/storage/media/Podcasts:/podcasts
```

## Docker logs

[booksonic.txt](https://github.com/linuxserver/docker-booksonic/files/4020568/booksonic.txt)
